---
title: Sac Desco
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'Sac DESCO (Design Collective) is a new interdisciplinary creative community
  in Sacramento, CA. '
baseurl: 
url: 
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
